name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . -t sbdb-student
          docker tag sbdb-student ${{ secrets.DOCKER_USERNAME }}/sbdb-student:${GITHUB_SHA}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/sbdb-student
